name: xt-siquirres
recipe: lamp
proxy:
  dbms:
    - dbms-xt-siquirres.lndo.site
config:
  webroot: .
services:
  appserver:
    config:
      php: php.ini
  dbms:
    type: phpmyadmin
    hosts:
      -  database
